async def execute(event, client, strings):
    msg = (
        "🌐 **Supported Sources**\n\n"
        "You can download from a wide variety of platforms, including:\n\n"
        "🎥 **Video Platforms**\n"
        "   • YouTube\n"
        "   • TikTok\n"
        "   • Instagram (Posts, Reels, Stories)\n"
        "   • Facebook (Videos, Reels)\n"
        "   • Vimeo\n"
        "   • Dailymotion\n"
        "   • Bilibili\n"
        "   • OK.ru\n\n"
        "🐦 **Social Media**\n"
        "   • Twitter (X)\n"
        "   • Reddit\n"
        "   • LinkedIn (videos)\n"
        "   • Pinterest\n\n"
        "🎶 **Music & Audio**\n"
        "   • SoundCloud\n"
        "   • Bandcamp\n"
        "   • Mixcloud\n\n"
        "🎮 **Streaming & Gaming**\n"
        "   • Twitch (clips & streams)\n"
        "   • Kick\n"
        "   • Niconico\n\n"
        "📰 **News & Others**\n"
        "   • BBC\n"
        "   • CNN\n"
        "   • IMDB (trailers)\n"
        "   • TED Talks\n\n"
        "Just send a link and the bot will handle the rest 🚀"
    )
    await event.reply(msg)
